In [50]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.datasets import fetch_california_housing

In [16]:
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Target'] = data.target
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [17]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Target      20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB


In [21]:
x = df.drop('Target',axis=1)
x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [23]:
y = df['Target']
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Target, Length: 20640, dtype: float64

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
model = LinearRegression()

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
model.fit(xtrain,ytrain)

LinearRegression()

In [34]:
y = model.predict(xtest)

In [35]:
y

array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251])

In [36]:
ytest

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: Target, Length: 4128, dtype: float64

In [41]:
from sklearn.metrics import mean_squared_error


In [43]:
mse = mean_squared_error(ytest,y)

In [46]:
mse*100

55.589159869524416

In [47]:
model.coef_

array([ 4.48674910e-01,  9.72425752e-03, -1.23323343e-01,  7.83144907e-01,
       -2.02962058e-06, -3.52631849e-03, -4.19792487e-01, -4.33708065e-01])

In [48]:
model.intercept_

-37.02327770606404

In [64]:
ridge_model = Ridge(alpha=0)
ridge_model.fit(xtrain,ytrain)

Ridge(alpha=0)

In [65]:
yRidge = model.predict(xtest)

In [66]:
mean_squared_error(ytest,yRidge)*100

55.589159869524416

In [67]:
from sklearn.linear_model import Lasso

In [68]:
lasso = Lasso(alpha=10.0)
lasso.fit(xtrain,ytrain)

Lasso(alpha=10.0)

In [69]:
yLasso = lasso.predict(xtest)

In [72]:
from sklearn.metrics import root_mean_squared_error

In [76]:
root_mean_squared_error(ytest,yLasso)

1.1446513708647494

In [77]:
from sklearn.linear_model import MultiTaskLasso
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# 🎯 Create fake data with 2 targets (height, weight)
X, y = make_regression(n_samples=100, n_features=5, n_targets=2, noise=0.1, random_state=42)

# ✂️ Split into train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 🧠 Initialize MultiTaskLasso
model = MultiTaskLasso(alpha=1.0)

# 🚀 Train it
model.fit(X_train, y_train)

# 🔮 Predict
y_pred = model.predict(X_test)

# 📉 Evaluate
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# 🧐 Check coefficients (shared across tasks)
print("Coefficients shape:", model.coef_.shape)  # (n_targets, n_features)
print("Coefficients:\n", model.coef_)


Mean Squared Error: 3.2051843616610527
Coefficients shape: (2, 5)
Coefficients:
 [[23.83312966 63.40748705 35.23339688  9.48661927 59.74205677]
 [15.48206625 55.84861926 97.48219142 14.39947209 23.56924007]]


In [80]:
X

array([[ 0.67959775,  1.0889506 ,  0.06428002, -0.71530371, -1.07774478],
       [-1.3044695 ,  0.38406545, -0.03269475, -0.08912004, -2.0674421 ],
       [-1.98756891,  0.8219025 ,  0.08704707,  0.09176078, -0.29900735],
       [ 1.30547881, -0.2176812 ,  1.09877685,  0.81350964,  0.82541635],
       [-0.0555477 ,  0.07409478,  1.62861555, -1.70338244, -1.38010146],
       [-0.47103831, -0.8222204 ,  0.24368721, -0.50694318,  0.24496657],
       [ 0.06751848, -0.74848654,  1.55115198,  1.17929718,  0.11567463],
       [ 0.2766908 , -0.88951443, -0.81581028,  0.34115197, -0.07710171],
       [-1.20029641, -0.79252074, -0.11473644,  0.86575519,  0.50498728],
       [ 0.33231401,  0.71161488, -1.12464209,  1.27767682, -1.53411417],
       [-1.19787789, -0.79287283, -0.10703036, -0.55364931, -1.03524232],
       [ 0.81252582, -0.47917424, -0.18565898, -1.19620662, -1.10633497],
       [-0.01901621,  0.31090757,  1.47535622, -0.15993853,  0.85765962],
       [-0.23458713, -1.46351495,  0.2